spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
      routes:
#        - id: example_route
#          uri: http://google.com
#          predicates:
#            - Path=/v1/google

management:
  endpoints:
    web:
      exposure:
        include: "*"