server:
  port: ${MS_GATEWAY_PORT:80}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway