server:
  port: ${MS_GATEWAY_PORT:80}

auth:
  service:
    uri: ${AUTH_SERVICE_URI:http://localhost:8090}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
        pool:
          max-connections: 500
          max-idle-time: 20000
          max-life-time: 60000
        wiretap: true

      routes:
        - id: ms-backend-route
          uri: ${MS_BACKEND_URI:http://localhost:8080}
          predicates:
            - Path=/api/v1/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

settings:
  auth:
    enabled: ${MS_AUTH_ENABLED:true}
