name: Deploy to vm

on:
  push:
    branches:
      - 'feature/deploy'

permissions:
  contents: read

jobs:
  publish:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tag: zhomt/msgateway:latest

  deploy:
    name: Deploy to target machine
    runs-on: [master-0]

    steps:
      - name: Pull image
        run: docker pull ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Run docker container from image
        run: docker run -d -p 8081:80 --name ms-gateway zhomt/msgateway:latest
