name: Deploy to vm

on:
  push:
    branches:
      - 'feature/deploy'

permissions:
  contents: read

jobs:
  publish:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish image to registry
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}

  deploy:
    name: Deploy to target machine
    runs-on: [self-hosted, master-0]

    steps:
      - name: Pull newer images from registry
        working-directory: ${{ secrets.VM_WORKING_DIR }}
        run: docker-compose -f ${{ secrets.VM_COMPOSE_FILE }} pull

      - name: Deploy docker stack
        working-directory: ${{ secrets.VM_WORKING_DIR }}
        run: docker stack deploy -c ${{ secrets.VM_COMPOSE_FILE }} deploy
